### ISSUE TITLE
Exception thrown when setting brightness

### ISSUE THREAD

**Issue by Nerpson** [jasonacox/tinytuya#164] opened 2022-07-30 00:40 UTC
Hey, I'm trying to create some party light algorithms, for fun.

For some reason, the brightness doesn't seem to do what I expect. The brightness percentage doesn't always work and it sometimes throws this unknown error:
![image](https://user-images.githubusercontent.com/9705025/181863326-2315311b-c291-437b-8803-cbca7a1aba6f.png)
I checked this `'24'` and it doesn't seem to be on my side. Every time it stops, the index is valid.

**Comment by jasonacox** [comment] 2022-07-30 01:43
Hi @Nerpson - thanks for opening this issue.  I'm not able to determine the cause based on that clip of your code and error. Can you help by running debug mode and perhaps a simple loop?  Here is an example:

```python
import tinytuya
import time

tinytuya.set_debug()

# Connect to Tuya BulbDevice
d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)  

# Show status of device
data = d.status()
print('\nCurrent Status of Bulb: %r' % data)

# Set to white
d.set_white()

# Dimmer Test
print('\nBrightness Control Test')
for level in range(11):
    print('    Level: %d%%' % (level*10))
    d.set_brightness_percentage(level*10)
    time.sleep(1)

print('\nDone')
```

**Comment by jasonacox** [comment] 2023-03-14 05:18
Closing due to age. Please re-open if this is still an issue.

**Closed by jasonacox** 2023-03-14 05:18 UTC
Labels: bug
