### ISSUE TITLE
Device discovery through vpn tunnel

### ISSUE THREAD

**Issue by NOV62** [jasonacox/tinytuya#172] opened 2022-08-30 06:21 UTC
Hello!  Thank you so much for your code - it works great!  But I have one question: some of the devices are on the same network (192.168.1.0), some on the other (192.168.10.0).  An SSTP tunnel is established between the networks, the firewall is disabled.  But 'tinytuya scan' does not see devices through the tunnel.  Can anything be done?

**Comment by NOV62** [comment] 2022-08-30 06:43
Извиняюсь, не прочитал  #159. Теперь понятно. Но не могу придумать, как исправить.

**Comment by jasonacox** [comment] 2022-08-31 04:10
Hi @NOV62 thanks for opening the issue.  You are right, #159 sounds like it may address the same issue for doing a forced scan where UDP would be blocked otherwise (e.g. VPN tunnel).  I'll assign this issue as an enhancement request.  Basically, I will update `scanner.py` to prompt the user for an optional netblock to scan.

**Comment by NOV62** [comment] 2022-08-31 12:13
It's going to be great!
I'm still just learning, because I don't know Python well, unfortunately I can't give my suggestions on the code.
Now I'm making a script for regular device status polling based on snapshot.py . I noticed that if the device does not respond (turned off),
there are long delays. set_socketRetryLimit() works, but set_socketTimeout() does not. set_socketTimeout(1), still waiting for 5 seconds.
In core.py fixed 
`415 ..... connection_timeout=1`
nothing has changed - there are 5 seconds left.

And another question, if you create several objects at the same time with the 'set_socket Persistent(True)' parameter, will it work?

**Comment by uzlonewolf** [comment] 2022-09-01 00:42
I'm now in the middle of a significant update to the scanner.  Making the brute-force search sockets non-blocking and dropping them into select.select() during the `while (count + counts) <= maxretry:` loop means scanning the entire /24 only adds ~1 second to the total run time.

I did hit a rather interesting issue though due to the shear number of devices I have.  It seems that if you have too many devices of the same version, the way that `while` loop backs off causes packets to back up and not get processed, which then blows up the script because the ip is not in deviceslist when it processes the brute-force results.  I'll probably rewrite it to just dump those sockets into the select() as well and let it process them as they come in.

An issue with the "additional netblock" thing is if it can't see the broadcasts then it cannot get the gwId and thus cannot poll it.  I don't remember, is there a packet that will cause it to respond with the gwId?  Maybe a heartbeat request?

**Comment by jasonacox** [comment] 2022-09-01 03:37
Great points @uzlonewolf !  Can't wait to see the update! 

If the user has the `device.json` file, we do have MAC to Device ID mapping for most devices.  That could be used to help map MAC to IP in the force method without the gwId from UDP packets. I haven't spent a lot of time looking at it so I could be missing something. 

Great catch on the UDP loop bug for 3.1 and 3.3 devices.  How many devices do you have now?  I have 34, mostly 3.3.  I often thought we should move to use python threads with one listening to UDP 6666 and another for UDP 6667, similar to what is done in server/server.py. Issue is always, "when do I stop listening?"  My may have the better appraoch.

**Comment by uzlonewolf** [comment] 2022-09-01 10:25
The problem is MAC addresses are Layer 2 while a VPN or "different subnet" means you only have Layer 3 access.  If you had Layer 2 access to get the MAC then you would be receiving the broadcasts and wouldn't need to scan, and if you need to scan because you don't have Layer 2 access then you cannot get the MAC since there is a router/server between you and the device.

Using the highly scientific method of "throw crap at it to see what sticks" I've found that with null payloads both HEART_BEAT and DP_QUERY provoke responses, however the HEART_BEAT response is a null packet that does not contain anything useful.  The DP_QUERY response however is an encrypted "data format error".  At this point the only thing I can think of is to load the list of local keys, filter out the ones we've already matched to a device, and brute-force the rest until we get it to decrypt.

As for the UDP loop, I currently have 19 devices, all v3.3.  Since they all spit out broadcasts every 5 seconds, that's ~3.8 packets per second; with no v3.1 devices it just sits there backing up every time that recvfrom() is called.  Putting those 2 sockets into select() will allow them to handle packets as they come in, and with that I'm thinking about changing the wait time to be a fixed 15-20 seconds just to make sure we don't miss any devices (they usually spit out a broadcast every 5 seconds, but I occasionally see them "miss" a period and take 10-11 seconds).

**Comment by jasonacox** [comment] 2022-09-02 05:57
Brilliant @uzlonewolf !  I'll keep an eye on your draft PR and add my comments.

**Comment by uzlonewolf** [comment] 2022-09-03 22:24
Well, I gave `get_mac_address()` a try, but as expected it just returns `None` if you only have Layer 3 access to the device.  Brute-force key detection is working rather well for my particular devices, however I can easily see lots of false positives.  Currently I am only looking at the padding - if we have say 15 bytes of padding and all 15 bytes decrypt to 0x0F then I think it's safe to say that we have the right key.  If the key is wrong but the very last byte happens to decrypt to 0x01 then we will have a problem if the rest of it decodes as valid UTF-8.

I also do not have any v3.1 devices to test.  The comments in core.py lead me to believe that they do not encrypt DP_QUERY packets which means this won't work for them.

Even after the key is found, it currently has no way of knowing what version the device is as that is not saved in devices.json and is also not included in the DP_QUERY response.  We might be able to figure it out by throwing version-specific commands at the device, but the code does not (yet?) do that.  After the force-scan is finished with the socket I have it keeping it open and passively listening for unsolicited status updates; these do have the version info prepended, so if we receive one then we can figure it out.  Very few devices emit these though, mainly thermostats, temperature sensors, and energy meters.

The Product ID is also unavailable as I have not found any way of requesting it from the device.  We can probably pull it from the cloud if we really need it though.

**Closed** 2023-01-14 05:14 UTC
Labels: enhancement
