### ISSUE TITLE
Timeout errors while toggling device state

### ISSUE THREAD

**Issue by MD5M-128** [jasonacox/tinytuya#11] opened 2020-11-30 13:03 UTC
I'm sure there's something I'm doing wrong here, but every time I try to set the state of my OutletDevice I get timeout errors. I checked this with the example `test.py` too. I followed all the instructions for getting the device key and checked through them multiple times, and watched the linked video as well. I can get the device state fine, I just can't set it, which is what leads me to believe it's something to do with the device key. Any help or explanation as to what is happening here would be much appreciated.

Thank you

**Comment by arrmo** [comment] 2020-12-01 01:49
Hi,

Just tried it here, using turn_on() and turn_off() ... works fine, no issues at all. What state are you trying to set?

**Comment by ear9mrn** [comment] 2020-12-17 13:41
Having the same issue here. Status is return ok but fails to turn switch on or off.

`
import tinytuya

d = tinytuya.OutletDevice('xxxx', 'xxxx', 'xxxx')
d.set_version(3.1)
data = d.status()
d.turn_off();

print('Dictionary %r' % data)
print('State (bool, true is ON) %r' % data['dps']['1'])
`

and response but switch does not change state. Works fine with app.

`
Dictionary {'devId': '13043158dc4f22eb0c47', 'dps': {'1': True, '11': 0}}
State (bool, true is ON) True

` 
Any suggestions?

Thanks.

Pete.

**Comment by jasonacox** [comment] 2020-12-20 05:50
Hi Pete, to control any Tuya device you need to make sure you have the correct device key.  A 3.1 device will provide status without the correct key so it can be misleading.  Did you run the Wizard (`python -m tinytuya wizard`) to get the keys (see [here](https://github.com/jasonacox/tinytuya#get-the-tuya-device-local_key)) or did you find them another way?

**Comment by ear9mrn** [comment] 2020-12-20 13:06
Hi Jason,

Many thanks for getting back to me. Yes, I did follow that process and as far as I can tell everything worked fine. When I ran the wizard it came back with a json response for my smart plug with a name, id and key which i then used to run the test.py script and it just timeout. I changed random letters in the key and get the same results so I assume the key the wizard is returning is incorrect for some reason. I will dig through the code to see if I can figure out what the problem is but my python skills are a little lacking...! 

Let me know if I can provide any more information to help diagnose the problem.

Pete.

**Comment by jasonacox** [comment] 2020-12-20 15:46
Thanks, Pete!  I think I found a bug.  For 3.1 devices, the hexdigest was set to trim [8:][:24] based on other tuya libraries. I adjusted it to hexdigest[8:][:16] for CONTROL commands.

I have pushed a new patched version (tinytuya 1.1.2), so try to upgrade see if this fixes the issue for you.

```
python3 -m pip install --upgrade tinytuya
```

Here is the updated section FYI: https://github.com/jasonacox/tinytuya/blob/917093b63fadc3f8c0b530ffecc8f2f80cb71e61/tinytuya/__init__.py#L419-L441

**Comment by ear9mrn** [comment] 2020-12-20 16:44
yep. working now......   :-)

Thanks,

Pete.

**Comment by jasonacox** [comment] 2020-12-21 04:36
Thanks, Pete!  I'll close this issue since it is linked to the new release.

**Closed by jasonacox** 2020-12-21 04:36 UTC
